name = "Dicke"
uuid = "4685f1ab-9fd1-4b8e-ac75-b8abf0894442"
authors = ["Sa√∫l Pilatowsky-Cameo <saulpilatowsky@ciencias.unam.mx>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Mamba = "5424a776-8be3-5c5b-a13f-3551f69ba0e6"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
WignerSymbols = "9f57e263-0b3d-5e2e-b1be-24f2bb48858b"

[compat]
CSV = "0.8"
GSL = "1"
QuadGK = "2"
DataStructures = "0.18"
SymEngine = "0.8"
DifferentialEquations = "6"
WignerSymbols = "2"
RecursiveArrayTools = "2"
ParameterizedFunctions = "5"
Mamba = "0.12"
Tables = "1"
ProgressMeter = "1"
DataFrames = "1"
Plots = "1"
LsqFit = "0.12"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
